steps:
#Build Firebase image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/myapp-ce183/firebase', './dockerfiles/firebase' ]
#Deploy Firebase using Token
- name: gcr.io/myapp-ce183/firebase
  args: [ 'deploy', '--project', myapp-ce183, '--token', '1//0g-sXpU2gQuSICgYIARAAGBASNwF-L9IrzjwbuWwvDBUEUoqUgw8r4afwN8VwtZuUoBWByT0Dhq3EqDyOI0vT8kRwoR_mnBpOvuI' ]
  # args: [ 'deploy', '--token', '1//0g-sXpU2gQuSICgYIARAAGBASNwF-L9IrzjwbuWwvDBUEUoqUgw8r4afwN8VwtZuUoBWByT0Dhq3EqDyOI0vT8kRwoR_mnBpOvuI']

# images:
# - 'gcr.io/[PROJECT ID]/firebase'
