swagger: '2.0'
info:
  title: Cloud Endpoints + GCF
  description: Sample API on Cloud Endpoints with a Google Cloud Functions backend
  version: 1.0.0
host: fajcloudtest.usindia.com
schemes:
  - https
produces:
  - application/json
paths:
  /CALLByHttp_asia_only:
    get:
      summary: Greet a user
      operationId: CALLByHttp_asia_only
      x-google-backend:
        address: https://asia-northeast1-myapp-ce183.cloudfunctions.net/CALLByHttp_asia_only
        protocol: h2
      responses:
        '200':
          description: A successful response
          schema:
            type: string
            